@host = http://localhost:3000/api/auth

###

GET http://localhost:3000/hello
Content-Type: application/json

###

POST {{host}}/register/5
Content-Type: application/json

{
    "account": "test1",
    "password": "tes234234ttest",
    "username": "test"
}

###

POST {{host}}/login
Content-Type: application/json

{
    "account": "test1",
    "password": "testtest"
}

###

GET {{host}}/5?token=123
Content-Type:application/json

###

GET {{host}}/notfound
Content-Type: application/json

###

GET {{host}}/empty
Content-Type: application/json

###

POST {{host}}/error
Content-Type: application/json

###

GET {{host}}/file
Content-Type: application/json

###

POST {{host}}/file
Content-Type: multipart/form-data; boundary=b

--b
Content-Disposition: form-data; name="user"

lai
--b
Content-Disposition: form-data; name="upload"; filename="test.txt"
Content-Type: text/plain

< ./assets/test.txt
--b
Content-Disposition: form-data; name="upload"; filename="test2.txt"
Content-Type: text/plain

< ./assets/test.txt
--b
Content-Disposition: form-data; name="upload2"; filename="test.txt"
Content-Type: text/plain

< ./assets/test.txt
--b
Content-Disposition: form-data; name="name"

ben
--b--